[project]
name = "cloud_lab2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio",
    "grpcio-tools",
    "prometheus-client>=0.23.1",
    "ruff>=0.14.6",
]
